### ISSUE TITLE
Build errors related to "service" reference not being found

### ISSUE THREAD

**Issue by alanwill** [ran-isenberg/aws-lambda-handler-cookbook#817]
**Describe the bug**
When running `cdk synth` or `make deploy` I'm getting the following error:
```
make deploy
mkdir -p .build/lambdas ; cp -r service .build/lambdas
cp: service: No such file or directory
make: *** [build] Error 1
```

**To Reproduce**
1. Run `cdk synth` or `make deploy`
2. See error

**Expected behavior**
Expect it to actually synthesize or deploy

**Screenshots**

**Additional context**
I believe this might be related to cookiecutter, will try to further troubleshoot and fix but hoping you'll know exactly what is going on before I do.

**Comment by alanwill** [comment]
I believe the issue is stemming from the [cookiecutter-serverless-python ](https://github.com/ran-isenberg/cookiecutter-serverless-python) repo and `{{cookiecutter.service_name}}` not being set in the Makefile where `service` is listed. Will look to you to validate and if correct, is there anywhere else where it needs to be update?

**Comment by ran-isenberg** [comment]
> I believe the issue is stemming from the [cookiecutter-serverless-python ](https://github.com/ran-isenberg/cookiecutter-serverless-python) repo and `{{cookiecutter.service_name}}` not being set in the Makefile where `service` is listed.
> 
> Will look to you to validate and if correct. I'm going through to look at other files where it may need to be updated as well like `cdk.json`

thanks! the problem is in make build where lke you said service (which is the default value) is not replaced with {{cookiecutter.service_name}}`.

**Comment by ran-isenberg** [comment]
fixed in https://github.com/ran-isenberg/cookiecutter-serverless-python/pull/24
Thanks again for reporting this regression bug @alanwill .

**Comment by alanwill** [comment]
Mostly all fixed but here's one that's still missing https://github.com/ran-isenberg/cookiecutter-serverless-python/blob/318c797a831ce2583a8fa3ee951d6ac0fce4dce6/%7B%7Bcookiecutter.repo_name%7D%7D/pyproject.toml#L30

BTW thank you for providing this useful repo as a resource to the community, it's been pretty interesting to learn from it.

**Comment by ran-isenberg** [comment]
yeah, that one doesnt matter. I tested a full clone/ deploy with a unique service and repo name (different from the default).


You are welcome ;)

**Comment by alanwill** [comment]
> yeah, that one doesnt matter. I tested a full clone/ deploy with a unique service and repo name (different from the default).

hmm that's odd, I had to change it for it to work otherwise I was getting an error when running I believe it was `make deploy`. Anyway, it was a simple fix and didn't run into any other issues. Thanks again!
